language: julia
os:
  - linux
julia:
  - nightly
  - 1.0
  - 0.7

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.add("PyCall")'
#  - julia --compilecache=no -e 'Pkg.clone(pwd()); Pkg.build("Simplices")'
  - julia -e 'ENV["PYTHON"] = ""; using Pkg; Pkg.build("PyCall")'
  - julia -e 'using Conda; Conda.add("scipy")'
  - julia -e 'using Pkg; Pkg.test()'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
